import type { Metadata } from "next";
import { Geist, Oswald, Unna} from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar";
import Footer from "./components/footer";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const oswald = Oswald({
  variable: "--font-oswald",
  weight: ["200","300","400","500","600","700"],
  subsets: ["latin"],
});

const unna = Unna({
  variable: "--font-unna",
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${oswald.variable} ${unna.variable} antialiased`}
      >
        <Suspense>
        <Navbar/>
        {children}
        <Footer/>
        </Suspense>
      </body>
    </html>
  );
}
